### ISSUE TITLE
ep2-us2 🎨create visuals for opening sequence

### ISSUE THREAD

**Issue by levinthiel** [levinthiel/KoroKoro#9]
## Value Proposition

**As a gamer**

**I want to have a beautiful opening sequence** 

**So that I can immerse myself into the game**.

## Description

![Image](https://github.com/user-attachments/assets/2a4526f5-6a95-42df-a8d3-0e42653b8406)

## Acceptance Criteria

- 7 images displaying various scenes based on the intro text
- each image is pixel art
- the images are primarily created and optimized for mobile viewport

## Tasks

- [ ] Create 7 images based on the intro text
  - [x]  space 1
  - [x] space 2
  - [x] Cosmic storm
  - [x] drift through space
  - [x] earth crash
  - [x] forest walk
  - [x] descision

**Comment by StephMode** [comment]
@levinthiel : that's a very well written and concise US 👍🏻

Just two comments:
- I changed the title of the US from "ep1-us5" to the current title to reflect the epic this US belongs to.
- I changed the third AC (previously: "- the main focus of the image is optimized for mobile") because my understanding is that we want to design and implement the images with mobile-first in mind.
